### ISSUE TITLE
Regarding the possibility of CT templates for post-contrast scans

### ISSUE THREAD

**Issue by shrikanth95** [muschellij2/high_res_ct_template#2]
Hello, 

This isn't really an "issue". I was curious about the feasibility of creating an atlas with post-contrast CT images using the same approach. Was the impediment just the availability of the post contrast scans? 

Thank you
Shrikanth

**Comment by muschellij2** [comment]
You should be able to do this in the same procedure, the only big issue is the skull/stripping/brain masking for the CT scans, depending if you wanted the vessels.  We didn't do this in this case because 1) high-resolution contrast CT wasn't the focus/cleaned (not sure if QURE500 has it), 2) skull stripping issue above, and 3) the use case we were working on was for non-contrast CT.
